allowBuilds:
  '@prisma/engines': false
  bcrypt: false
  core-js: false
  msgpackr-extract: false
  msw: false
  prisma: false
  sharp: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
